version: '2.0'
services:
  stat-server:
    build: ./stat/stat-server
    image: stat-server
    container_name: stat-server
    ports:
    - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:9.5-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: main
    image: main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  ewm-db:
    image: postgres:9.5-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password